name: Google Cloud Run Deploy
# https://github.com/google-github-actions/setup-gcloud
# (source: https://medium.com/swlh/deploying-a-react-app-to-google-cloud-run-with-github-actions-ae24ac6cb85a)
on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCR_PROJECT }}
  RUN_REGION: northamerica-northeast1
  SERVICE_NAME: hello-react-app

jobs:
  build:
    name: Build React App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Setup Node.js (NPM)
        uses: actions/setup-node@master
        with:
          node-version: '12.x'

      - name: Use cached node_modules
        uses: actions/cache@master
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: (cd hello-app; npm install --frozen-lockfile)
        env:
          CI: true

      - name: Build Development
        run: (cd hello-app; npm run build)
        env:
          CI: false

      - name: Archive Production Artifact
        uses: actions/upload-artifact@main
        with:
          name: build
          path: hello-app/build

  deploy-gcr:
    name: Deploy to GCR
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Download Artifact
        uses: actions/download-artifact@main
        with:
          name: build
          path: hello-app/build

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: hello-app/build

      # https://github.com/google-github-actions/setup-gcloud (README.md)
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCR_SA_KEY }}
          project_id: ${{ secrets.GCR_PROJECT }}
          export_default_credentials: true

      # Build and push image to Google Container Registry
      - name: Build & Push
        run: |-
          gcloud builds submit \
            --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"
        working-directory: hello-app

      # Deploy image to Cloud Run
      - name: Deploy GCR
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
            --region "$RUN_REGION" \
            --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
            --platform "managed" \
            --allow-unauthenticated
